// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjraayhrgnwxtpykhkrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqcmFheWhyZ253eHRweWtoa3JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNzYyODUsImV4cCI6MjA3MTY1MjI4NX0.aCxMnolk45VizCgZAw8gkQaV1WAXGzAcfu-KhbgFtJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});